function [sum] = sum_of_pairs(sequence_1, sequence_2, actual_zone, windows_size)
    sum = 0.0;
    for base_index = 0 : windows_size - 1
        sum = sum + ...
        compare_nucleotides( ...
        sequence_1.Sequence(actual_zone.s1_start + base_index), ...
        sequence_2.Sequence(actual_zone.s2_start + base_index) ...
        );
    end
end

